### ISSUE TITLE
README: Update to its

### ISSUE THREAD

**Issue by denisecase** [Vikas2004/locator#3]
In the README text below, 

- change it's to its (like his, hers) rather than the contraction.
- change help to helps
- change confirm to confirms
- add comma after it (How cool is it, right?)

Very cool! 

This application help it's users to find the treasures based on the treasure location and it validates the user location when it matches with the treasure location and confirm it to the user with UI effects. How cool is it right?

**Comment by Vikas2004** [comment]
Thank you for the valuable insights, Dr.Case. We have fixed the errors.
